services:
  timeoff-manager-frontend:
    image: node:18-alpine
    container_name: timeoff-manager-frontend
    restart: unless-stopped
    working_dir: /app
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL:-http://localhost:8000/}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "npm install &&
             npm run dev -- --host 0.0.0.0 --port 3000"
